# Generated by Django 4.2.3 on 2023-07-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='type',
        ),
    ]
